config/routes.rb
Rails.application.routes.draw do
  get '/', to: redirect('/posts')
  resources :posts do 
    member do
      put :publish
      put :unpublish
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  after_create :create_post_id
  before_save :update_post_id
  before_save :save_version

  COLUMNS_THAT_TRIGGER_NEW_VERSION = ["title", "description"]

  default_scope { order('post_id, published_at desc') } 
  scope :last_published, -> { joins('join (select distinct on (inner_posts.post_id) inner_posts.id from posts as inner_posts order by inner_posts.post_id, inner_posts.published_at desc nulls last) as published_posts on published_posts.id = posts.id')}


  has_many :versions, class_name: "Post", primary_key: "post_id", foreign_key: 'post_id'

  #has_many :post_versions, -> { where post_id: 22 }, class_name: 'Post'
  has_one :last_version, -> { last_published }, class_name: 'Post'

  attr_accessor :is_clone

  def update_post_id
    self.post_id ||= self.id
  end

  def create_post_id
    return if post_id
    update(post_id: id)
  end

  # def versions
  #   self.class.where(post_id: self.post_id).where.not(id: self.id)
  # end

  def save_version
    return true if (changed_attributes.keys & COLUMNS_THAT_TRIGGER_NEW_VERSION).size == 0
    
    return if is_clone? #avoid nasty recursive loops
    return unless published? #don't create new version, unless the version itself is published
    self.version_clone
    self.restore_attributes
  end

  def published?
    published_at.present?
  end

  def publish
    published_at = Time.now
    self
  end

  def unpublish
    published_at = nil
    self
  end

  def publish!
    update(published_at: Time.now)
  end

  def unpublish!
    update(published_at: nil)
  end

  def is_clone?
    is_clone == true
  end

  def version_clone
    version_clone = dup
    version_clone.is_clone = true
    version_clone.published_at = nil
    version_clone.save
    version_clone
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :publish, :unpublish]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:versions).last_published
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def publish
    respond_to do |format|
      if @post.publish!
        format.html { redirect_to posts_path, notice: 'Post was successfully published.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { redirect_to posts_path }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def unpublish
    respond_to do |format|
      if @post.unpublish!
        format.html { redirect_to posts_path, notice: 'Post was successfully unpublished.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { redirect_to posts_path }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tricky</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :html => { :class => "form-horizontal post" } do |f| %>

    <% if @post.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@post[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@post[:description]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            posts_path, :class => 'btn btn-default' %>

<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Type</th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:post_id) %></th>
      <th><%= model_class.human_attribute_name(:published_at) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |main_post| %>
    
      <% post_versions = main_post.versions %>
      
      <% main_class_color = main_post.published? ? "green" : "red" %>
      <% ([*main_post] + ([*post_versions] - [*main_post])).each do |post| %>
    

        <% main_version = post.id == main_post.id %>
        <% current_class_color = main_version ? main_class_color : "gray" %>
        <tr style='background-color:<%= current_class_color %>'>
          <td><%= main_version ? 'Main' : "History" %></td>
          <td><%= link_to post.id, post_path(post) %></td>
          <td><%= post.post_id %></td>
          <td><%= post.published_at %></td>
          <td><%= post.title %></td>
          <td><%= post.description %></td>
          <td><%=l post.created_at %></td>
          <td>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_post_path(post), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        post_path(post),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>

            <% if post.published? %>
              <%= link_to t('.unpublish', :default => t("helpers.links.unpublish")),
                          unpublish_post_path(post),
                          :method => :put,
                          #:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Unpublish?')) },
                          :class => 'btn btn-xs btn-danger' %>
            <% else %>
              <%= link_to t('.publish', :default => t("helpers.links.publish")),
                          publish_post_path(post),
                          :method => :put,
                          #:data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Publish?')) },
                          :class => 'btn btn-xs btn-danger' %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_post_path,
            :class => 'btn btn-primary' %>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @post.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>